# Generated by Django 4.2.13 on 2024-07-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False, verbose_name='url')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('intro', models.CharField(max_length=500, verbose_name='简介')),
                ('browse', models.IntegerField(verbose_name='播放量')),
                ('danmu', models.IntegerField(verbose_name='弹幕')),
                ('num_comments', models.IntegerField(verbose_name='评论数')),
                ('num_likes', models.IntegerField(verbose_name='点赞')),
                ('num_coins', models.IntegerField(verbose_name='投币')),
                ('num_collect', models.IntegerField(verbose_name='收藏')),
                ('num_share', models.IntegerField(verbose_name='分享')),
                ('v_class', models.CharField(default=' ', max_length=20, verbose_name='分区')),
                ('v_detailed_class', models.CharField(default=' ', max_length=20, verbose_name='细分分区')),
                ('v_split', models.CharField(default=' ', max_length=1000, verbose_name='分词')),
                ('comments1', models.CharField(default=' ', max_length=1000)),
                ('comments2', models.CharField(default=' ', max_length=1000)),
                ('comments3', models.CharField(default=' ', max_length=1000)),
                ('comments4', models.CharField(default=' ', max_length=1000)),
                ('comments5', models.CharField(default=' ', max_length=1000)),
                ('tags', models.ManyToManyField(related_name='videos', to='recommend.tag')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'video',
            },
        ),
    ]
